### ISSUE TITLE
命令行启动（不是IIS）后 addresses.Addresses拿不到地址

### ISSUE THREAD

**Issue by weibinlong** [zengqinglei/Creekdream.Discovery.Consul#1]
命令行启动（不是用VS）后 addresses.Addresses拿不到地址的问题，也就是addresses.Addresses的集合数为0，所以addresses.Addresses.First()是报错（ConsulApplicationBuilderExtensions.cs文件52行中）。
在这加上UseUrls后正常。
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
           .UseUrls("http://localhost:8081")
            .UseStartup<Startup>();
但不想加上UseUrls。所以请问大神有什么解决方便吗？
var addresses = app.ServerFeatures.Get<IServerAddressesFeature>();好像和IIS 寄宿方式、Hosting寄宿有关。

**Comment by zengqinglei** [comment]
如果不加的话，你可以考虑在appsetting.json中配置ServiceUri的地址，你看符合你得要求么？
_十一休假没及时回复，不好意思！_
